### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by codeblv** [bhaptics/tactosy-sharp#11]
* UnityEditor not found on build

**Comment by neomegas** [comment]
The UnityEditor classes should be covered with preprocessor directives to cut this code out when building for the target platform. If not, you will get compilation errors.

So in TactosyEditor.cs

    #if UNITY_EDITOR
    using UnityEditor; 
    #endif
    using UnityEngine;
    namespace Tactosy.Unity
    {
    #if UNITY_EDITOR
    [CustomEditor(typeof(Manager_Tactosy))]
    public class TactosyEditor : Editor
    {
        public override void OnInspectorGUI()
        {
            DrawDefaultInspector();

            Manager_Tactosy tactosyManager = (Manager_Tactosy) target;

            foreach (var mappings in tactosyManager.FeedbackMappings)
            {
                var key = mappings.Key;

                if (GUILayout.Button(key))
                {
                    tactosyManager.Play(key);
                }
            }
            if (GUILayout.Button("Turn Off"))
            {
                tactosyManager.TurnOff();
            }
        }
    }
    #endif
    }

Lastly, make sure any UI related code on GameObject disasbled! (for example, DebugUI.cs in SteamVR)
